config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :vendors

  resources :products, only: %i[index show]

  namespace :vendors do
    resources :products, param: :slug
    resources :categories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  get 'cart', to: 'carts#show'
  post 'carts/add'
  post 'carts/remove'
end

app/views/shared/_footer.html.erb
  <!-- ***** Footer Start ***** -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
          <div class="first-item">
              <div class="logo">
                  <%= image_tag 'white-logo.png' %>
              </div>
              <ul>
                  <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                  <li><a href="#">hexashop@company.com</a></li>
                  <li><a href="#">010-020-0340</a></li>
              </ul>
          </div>
      </div>
      <div class="col-lg-3">
          <h4>Shopping &amp; Categories</h4>
          <ul>
              <li><a href="#">Men’s Shopping</a></li>
              <li><a href="#">Women’s Shopping</a></li>
              <li><a href="#">Kid's Shopping</a></li>
          </ul>
      </div>
      <div class="col-lg-3">
          <h4>Useful Links</h4>
          <ul>
              <li><a href="#">Homepage</a></li>
              <li><a href="#">About Us</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><%= link_to 'Become a Vendor', vendors_products_path %></li>
              <% if vendor_signed_in? %>
                <li><%= link_to "logout", destroy_vendor_session_path, method: :delete %></li>
              <% end %>
          </ul>
      </div>
      <div class="col-lg-3">
          <h4>Help &amp; Information</h4>
          <ul>
              <li><a href="#">Help</a></li>
              <li><a href="#">FAQ's</a></li>
              <li><a href="#">Shipping</a></li>
              <li><a href="#">Tracking ID</a></li>
          </ul>
      </div>
      <div class="col-lg-12">
          <div class="under-footer">
              <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved.

              <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
              <ul>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                  <li><a href="#"><i class="fa fa-behance"></i></a></li>
              </ul>
          </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header-area header-sticky">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="main-nav">
          <!-- ***** Logo Start ***** -->
          <a href="index.html" class="logo">
            <%= image_tag 'logo.png', alt: '' %>

          </a>
          <!-- ***** Logo End ***** -->
          <!-- ***** Menu Start ***** -->
          <ul class="nav">
              <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
              <li class="scroll-to-section"><%= link_to 'Shop', products_path %></li>
              <li class="scroll-to-section"><a href="#men">Men's</a></li>
              <li class="scroll-to-section"><a href="#women">Women's</a></li>
              <li class="scroll-to-section"><a href="#kids">Kid's</a></li>
              <li class="submenu">
                  <a href="javascript:;">Pages</a>
                  <ul>
                      <li><a href="about.html">About Us</a></li>
                      <li><a href="products.html">Products</a></li>
                      <li><a href="single-product.html">Single Product</a></li>
                      <li><a href="contact.html">Contact Us</a></li>
                  </ul>
              </li>
              <li class="submenu">
                  <a href="javascript:;">Features</a>
                  <ul>
                      <li><a href="#">Features Page 1</a></li>
                      <li><a href="#">Features Page 2</a></li>
                      <li><a href="#">Features Page 3</a></li>
                      <li><a rel="nofollow" href="https://templatemo.com/page/4" target="_blank">Template Page 4</a></li>
                  </ul>
              </li>
              <li class="scroll-to-section"><a href="#explore">Explore</a></li>
                  <%# render partial: 'carts/cart' if @render_cart %>
              <li>
                <!-- <button type="button" class="btn btn-demo" data-bs-toggle="modal" data-bs-target="#exampleModal"> -->
                <%= link_to cart_path do %>
                  <i class="fa fa-shopping-cart"></i>
                <% end %>
                <!-- </button> -->
              </li>
          </ul>
          <a class='menu-trigger'>
              <span>Menu</span>
          </a>
          <!-- ***** Menu End ***** -->
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/shared/_preloader.html.erb
<div id="preloader">
  <div class="jumper">
    <div></div>
    <div></div>
    <div></div>
  </div>
</div>