config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :vendors

  resources :products, only: %i[index show]

  namespace :vendors do
    resources :products, param: :slug
    resources :categories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  get 'cart', to: 'carts#show'
  post 'carts/add'
  post 'carts/remove'
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum(&:total)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show; end

  # rubocop:disable Metrics/AbcSize
  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(:quantity)
    elsif quantity <= 0
      @cart.orderables.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart', partial: 'carts/cart', locals: { cart: @cart })]
      end
    end
  end
  # rubocop:enable Metrics/AbcSize

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart', partial: 'carts/cart', locals: { cart: @cart })]
      end
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  <% if @cart.orderables.count > 0 %>
    <%= render 'carts/orderable' %>
    <p>Total: <%= @cart.total %></p>
  <% else %>
    <p>Your Cart is empty</p>
  <% end %>
<% end %>

app/views/carts/_orderable.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product =  orderable.product %>
  <div class="total">
    <div class="main-border-button">
      <%= form_with(url: carts_add_path) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <div class="field">
          <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
        </div>
        <div class="actions">
          <%= f.submit "Add to Cart", class:'main-dark-button' %>
        </div>
      <% end %>
      <%= form_with(url: carts_remove_path) do |f| %>
        <%= f.hidden_field :id, value: orderable.id %>
        <%= f.submit "X", class:'main-dark-button' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<div class="page-heading about-page-heading" id="top">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="inner-content">
            <h2>Shopping Cart</h2>
            <span>Awesome, lets order all this</span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="contact-us">
    <div class="container">
     <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product Image</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total</th>
      <th scope="col">Update</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.orderables.each do |orderable| %>
      <% product = orderable.product %>
      <tr>
         <div id="cart-#<%= product.id %>">

          <th scope="row resize">
            <% if nil? %>
              <%= image_tag product.images.first, class: 'resize ' %>
            <% else %>
              No Product Image
            <% end %>
          </th>
          <td><%= product.title %></td>
          <td><%= product.currency %><%= product.price %></td>
          <td><%= orderable.quantity %></td>
           <td><%= orderable.total %></td>
           <td>
             <%= form_with(url: carts_add_path) do |f| %>
              <%= f.hidden_field :id, value: product.id %>
              <div class="input-group">
                <%= f.number_field :quantity, value: orderable.quantity, min:0, class: "form-control" %>
              <%= f.submit "update", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </td>
          <td>
            <%= form_with(url: carts_remove_path) do |f| %>
              <%= f.hidden_field :id, value: orderable.id %>
              <%= f.submit "Remove from Cart", class: 'btn btn-danger' %>
            <% end %>
          </td>

        </div>
      </tr>
    <% end %>
  </tbody>
</table>

    </div>
</div>