config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :vendors

  resources :products, only: %i[index show]

  namespace :vendors do
    resources :products, param: :slug
    resources :categories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  get 'cart', to: 'carts#show'
  post 'carts/add'
  post 'carts/remove'
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  price       :float
#  currency    :string
#  vendor_id   :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Product < ApplicationRecord
  belongs_to :vendor

  validates :vendor_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :currency, presence: true

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :orderables
  has_many :carts, through: :orderables
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/vendors/products_controller.rb
# frozen_string_literal: true

module Vendors
  class ProductsController < MainController
    def index
      @products = current_vendor.products.all
    end

    def show
      @product = current_vendor.products.find_by(title: params[:slug])
    end

    def new
      @product = current_vendor.products.new
    end

    def create
      @product = current_vendor.products.new(product_params.except(:categories))
      create_or_delete_products_categories(@product, params[:product][:categories])

      if @product.save
        redirect_to vendors_product_path(@product)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @product = current_vendor.products.find(params[:id])
    end

    def update
      @product = current_vendor.products.find(params[:id])
      create_or_delete_products_categories(@product, params[:product][:categories])

      if @product.update(product_params.except(:categories))
        redirect_to vendors_product_path(@product)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product = current_vendor.products.find(params[:id])
      @product.destroy

      redirect_to root_path, status: :see_other
    end

    private

      def product_params
        params.require(:product).permit(:title, :description, :price, :currency, :tags)
      end

      def create_or_delete_products_categories(product, categories)
        product.product_categories.destroy_all
        categories = categories.strip.split(',')
        categories.each do |category|
          product.categories << Category.find_or_create_by(name: category)
        end
      end
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/vendors/products_helper.rb
# frozen_string_literal: true

module Vendors
  module ProductsHelper
  end
end

app/views/products/index.html.erb
<div class="page-heading" id="top">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="inner-content">
          <h2>Check Our Products</h2>
          <span>Awesome &amp; Creative HTML CSS layout by TemplateMo</span>
        </div>
      </div>
    </div>
  </div>
</div>
<section class="section" id="products">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h2>Our Latest Products</h2>
                    <span>Check out all of our products.</span>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
          <% @products&.each do |product| %>
            <div class="col-lg-4">
                <div class="item">
                    <div class="thumb">
                        <div class="hover-content">
                            <ul>
                                <li><%= link_to product_path(product) do %>
                                        <i class="fa fa-eye"></i>
                                    <% end %>
                                </li>
                                <li><a href="single-product.html"><i class="fa fa-star"></i></a></li>
                                <li><a href="single-product.html"><i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                        <%= image_tag 'men-01' %>
                    </div>
                    <div class="down-content">
                        <h4><%= product.title %></h4>
                        <span><%= product.price %> <%= product.currency %></span>
                        <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                        </ul>
                    </div>
                </div>
              <%= link_to vendors_product_path(product) do %>
              <% end %>
            </div>
          <% end %>
          <div class="col-lg-12">
            <div class="pagination">
              <ul>
                <li>
                    <a href="#">1</a>
                </li>
                <li class="active">
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">></a>
                </li>
              </ul>
            </div>
          </div>
        </sdiv>
    </div>
</section>
<!-- ***** Products Area Ends ***** -->

app/views/products/show.html.erb
<div class="page-heading" id="top">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <div class="inner-content">
                  <h2>Single Product Page</h2>
                  <span>Awesome &amp; Creative HTML CSS layout by TemplateMo</span>
              </div>
          </div>
      </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-8">
      <div>
      </div>
      <div>

      </div>
      <div>

      </div>
      <div>
        <strong> Categories</strong>
      </div>
    </div>
    <div class="col-4">
    </div>
  </div>
</div>

    <!-- ***** Main Banner Area End ***** -->

    <!-- ***** Product Area Starts ***** -->
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                <div class="left-images">
                    <%= image_tag 'single-product-01.jpg' %>
                    <%= image_tag 'single-product-02.jpg' %>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="right-content">
                    <h4><%= @product.title %></h4>
                    <span class="price"><%= @product.price %> <%= @product.currency %></span>
                    <ul class="stars">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                    <span><%= @product.description %></span>
                    <div class="quote">
                      <% @product.categories.each do |category| %>
                        <i class="fa fa-quote-left"></i><p><%= category.name %></p>
                      <% end %>
                    </div>
                    <div class="quantity-content">
                        <div class="left-content">
                            <h6>No. of Orders</h6>
                        </div>
                        <div class="right-content">
                            <div class="quantity buttons_added">
                                <!-- <input type="button" value="-" class="minus"><input type="number" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode=""><input type="button" value="+" class="plus"> -->
                            </div>
                        </div>
                    </div>
                    <div class="total">
                      <div class="main-border-button">
                        <%= form_with(url: carts_add_path) do |f| %>
                          <%= f.hidden_field :id, value: @product.id %>
                          <div class="field">
                            <%= f.number_field :quantity, value: 0, min: 1 %>
                          </div>
                          <div class="actions">
                            <%= f.submit "Add to Cart", class:'main-dark-button' %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>